### ISSUE TITLE
(Question) SDR support  

### ISSUE THREAD

**Issue by alphafox02** [fventuri/linrad#1]
No issue at all, but I did just stumble upon this build while reading the linrad mailing lists and seeing your posts. I just tried the stock Linrad a few minutes ago and was able to receive and demodulate between 6-7Mhz w/ the Airspy HF. I have the rsp1a to test with as well. 

My question, having not built or tested your fork yet, is if all the other SDR support remains? Also just wanted to say thanks for the development you do on SoapySDR etc.

**Comment by fventuri** [comment]
@alphafox02 - thanks for the nice words about SoapySDR and the other projects I am working on.

As per your question about the SDRplay API version 3 code for Linrad, it is just a new driver in addition to the existing ones (AirSpy, RTL-SDR,  BladeRF, etc), so you can build this version and use it with the current hardware you have (I left also the existing support for SDRplay API version 2, so in theory you could run both versions of the SDRplay API with the same executable).

One of the most interesting features of this version is that, if you have an RSPduo, you can run it in diversity reception using both tuners at the same time (which wasn't possible with the the previous version of Linrad).

Franco

**Comment by alphafox02** [comment]
Your very welcome. I need to go update Soapy Sdrplay while I’m thinking about it.

I’ll close this out and test it out on my end, still have no idea what all linrad can do and just went with the gui build so I could see what I was doing. I was donated a duo but some time ago contacted it to someone else for further development, I probably should’ve held onto it a little longer.
